name: test37
channels:
  - conda-forge
  - udst
  - https://conda.anaconda.org/mutirri
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - boost-cpp=1.72.0=h0caebb8_0
  - bzip2=1.0.8=hfa6e2cd_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cfitsio=3.470=hfa6e2cd_2
  - click=7.1.1=pyh8c360ce_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - curl=7.69.1=h1dcc11c_0
  - cycler=0.10.0=py_2
  - expat=2.2.9=he025d50_2
  - fiona=1.8.13=py37hb7fdc2d_0
  - freetype=2.10.1=ha9979f8_0
  - freexl=1.0.5=hd288d7e_1002
  - gdal=3.0.4=py37hd44be9e_8
  - geopandas=0.7.0=py_1
  - geos=3.8.1=he025d50_0
  - geotiff=1.5.1=h3d29ae3_10
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.64.2=he4de6d7_0
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.6=nompi_ha405e13_100
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - intel-openmp=2020.0=166
  - jpeg=9c=hfa6e2cd_1001
  - kealib=1.4.13=h3b59ab9_1
  - kiwisolver=1.2.0=py37heaa310e_0
  - krb5=1.17.1=hdd46e55_0
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libcurl=7.69.1=h1dcc11c_0
  - libffi=3.2.1=h6538335_1007
  - libgdal=3.0.4=h6f60a84_8
  - libiconv=1.15=hfa6e2cd_1006
  - libkml=1.3.0=h7e985d0_1011
  - liblapack=3.8.0=15_mkl
  - libnetcdf=4.7.4=nompi_h256d12c_102
  - libpng=1.6.37=hfe6a214_1
  - libpq=12.2=hd9aa61d_1
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h51df0ed_1038
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.1.0=h885aae3_6
  - libwebp-base=1.1.0=hfa6e2cd_3
  - libxml2=2.9.10=h9ce36c8_0
  - lz4-c=1.9.2=h33f27b4_0
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37h911224e_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - numpy=1.18.1=py37h90d3380_1
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1g=he774522_0
  - pandas=1.0.3=py37h3bbf574_1
  - patsy=0.5.1=py_0
  - pcre=8.44=h6538335_0
  - pip=20.0.2=py_2
  - poppler=0.87.0=h0cd1227_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=he14cc48_1
  - proj=7.0.0=haa36216_3
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.0=py37he833962_1
  - pyqt=5.12.3=py37h6538335_1
  - python=3.7.6=h60c2a47_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - qt=5.12.5=h7ef1ec2_0
  - rtree=0.9.4=py37h804a536_1
  - scipy=1.4.1=py37h9439919_0
  - setuptools=46.1.3=py37hc8dfbb8_0
  - shapely=1.7.0=py37he1cf020_3
  - six=1.14.0=py_1
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.11.1=py37h8055547_1
  - tbb=2018.0.5=he980bc4_0
  - tiledb=1.7.7=h0b90766_1
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.4=py37hfa6e2cd_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.34.2=py_1
  - wincertstore=0.2=py37_1003
  - xerces-c=3.2.2=h6538335_1004
  - xz=5.2.5=h2fa13f4_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=h9f78265_3
  - pip:
    - hapi-nile==0.1.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: E:\ProgramData\Conda3\envs\test37

