channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - affine
  - fiona
  - proj
  - gdal
  - pandas
  - geopandas
  - matplotlib
  - python
  - scipy
  - shapely
  - statsmodels
  - rasterio
  - rasterstats
  - oasis
  - netCDF4
  - scikit-learn
  - scikit-image
  - ecmwf-api-client
  - joblib
  #- hapi
  - pip:
    - numpy
    - pyproj
    - hapi-nile
    #- git+https://github.com/MAfarrag/HAPI.git
